### PR TITLE
chore(chart): update example values for staticPasswords

### PR DESCRIPTION
**Pull request by kkaneda**
What Dex expects is found below:

- https://github.com/dexidp/dex/blob/master/examples/config-dev.yaml#L162
- https://github.com/dexidp/dex/blob/master/cmd/dex/config.go#L96

The current example is based on our own mapping that we used to have:

- https://github.com/llmariner/rbac-manager/blob/ab47e8099d87dc0beffb77cb81aec407c0c69e6a/deployments/dex-server/templates/configmap.yaml#L70

### CODE REVIEW

**Review by Ladicle — APPROVED** [review]
Executing `run generate-chart-schema` will also update the description of the values schema.

BTW, I didn’t realize, but the `make git-clean-check` command does not reflect other target results.

**Comment by kkaneda** [comment]
Hm, that's strange indeed. Looks like the behavior of `helm lint` is different. 

I got the following locally:

```
➜ make lint

cd ./deployments/dex-server && helm-tool lint
No errors found
helm lint ./deployments/dex-server
==> Linting ./deployments/dex-server

1 chart(s) linted, 0 chart(s) failed
cd ./deployments/rbac-server && helm-tool lint
No errors found
helm lint ./deployments/rbac-server
==> Linting ./deployments/rbac-server

1 chart(s) linted, 0 chart(s) failed
git diff

Δ deployments/dex-server/values.schema.json
```

I opened https://github.com/llmariner/rbac-manager/pull/124 for testing, but that one doesn't fail. 

```
...
No errors found
helm lint ./deployments/dex-server
==> Linting ./deployments/dex-server
1 chart(s) linted, 0 chart(s) failed
cd ./deployments/rbac-server && helm-tool lint
No errors found
helm lint ./deployments/rbac-server
==> Linting ./deployments/rbac-server
1 chart(s) linted, 0 chart(s) failed
```

**Comment by kkaneda** [comment]
Maybe `git_dirty` runs after `helm lint`.

```
git_dirty := $(shell git status -s)

git-clean-check:
ifneq ($(git_dirty),)
	git diff
	@echo "Git repository is dirty!"
	@false
endif
```

**Comment by Ladicle** [comment]
It seems that way. 

I found the same question about this.
https://stackoverflow.com/questions/57508742/makefile-target-to-check-for-clean-git-diff#57509208

**Comment by kkaneda** [comment]
i see :(  we can fix later..

**Pull request merged**
